{
 "title": "CHT Admin Extra SQL",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cht_instance",
    "label": "CHT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Days since last successful purge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(purge_logs_duration_minutes{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purging events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(purge_logs_duration_minutes{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Form completions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(form_completions_load_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(form_completions_complete_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Form completions by user",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(form_completions_load_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(form_completions_complete_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback docs by type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "feedback_docs_source_count{cht_instance=\"$cht_instance\", source=\"manual\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "feedback_docs_source_count{cht_instance=\"$cht_instance\", source=\"automatic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manual feedback docs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "manual_feedback_docs_detail_count{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Automatic feedback docs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "automatic_feedback_docs_detail_count{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days since successful purge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dwh_last_successful_purge_seconds{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users with insufficient Chrome version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 30 },
   "targets": [
    {
     "expr": "last_over_time(users_with_insufficient_chrome_version_user_name{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users with Insufficient Disk Space",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "users_with_insufficient_disk_free_storage_mb{cht_instance=\"$cht_instance\"}"
    },
    {
     "expr": "dwh_form_completions_last_60_days_complete_percentage{cht_instance=\"$cht_instance\"}"
    },
    {
     "expr": "dwh_form_completions_last_60_days_incomplete_count{cht_instance=\"$cht_instance\"}"
    }
   ]
  },
  {
   "title": "Replication Failures",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "last_over_time(replication_by_status_replication_failure_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication failure reasons",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dwh_replication_failure_reasons_count{cht_instance=\"$cht_instance\"}"
    }
   ]
  },
  {
   "title": "Replication Errors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "last_over_time(replication_by_status_replication_error_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Success",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "last_over_time(replication_by_status_replication_success_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "{{period_start}}"
    }
   ]
  },
  {
   "title": "Denied Replications",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "last_over_time(replication_by_status_replication_denied_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "{{period_start}}"
    }
   ]
  },
  {
   "title": "# docs replicated per day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "replication_activity_delta_docs{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days since last sync",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "last_over_time(chw_engagement_days_since_last_sync{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway state",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "gateway_health_due{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful initial replications",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "last_over_time(initial_replications_count_initial_replications{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "SMS states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sms_error_and_users_docs_replication_due{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid docs",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "last_over_time(invalid_docs_invalid_doc_count{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid doc errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 85 },
   "targets": [
    {
     "expr": "invalid_doc_errors_count{cht_instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "last_over_time(tasks_by_state_ready{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draft Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "last_over_time(tasks_by_state_draft{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cancelled Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "last_over_time(tasks_by_state_cancelled{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "last_over_time(tasks_by_state_completed{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "last_over_time(tasks_by_state_failed{cht_instance=\"$cht_instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}